################ EMF sample build script ##################
Import('env')

target_os = env.get('TARGET_OS')
emf_sample_env = env.Clone()

######################################################################
# Build flags
######################################################################
emf_sample_env.AppendUnique(CPPPATH=[
	'../extlibs/zmq',
	'../protobuf',
    '../include',
    '../src'
])

emf_sample_env.AppendUnique(
    CXXFLAGS=['-O2', '-g', '-Wall', '-fmessage-length=0', '-std=c++0x', '-I/usr/local/include'])

emf_sample_env.AppendUnique(LIBS=['emf', 'protobuf'])

####################################################################
# Source files and Targets
######################################################################
emfpublisher = emf_sample_env.Program('publisher', 'publisher.cpp')
emfsubscriber = emf_sample_env.Program('subscriber', 'subscriber.cpp')